name: fitnesstracker
description: "Fitness Tracker App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  workmanager: ^0.9.0
  health:
    git:
      url: https://github.com/cph-cachet/flutter-plugins.git
      path: packages/health

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/